name: Deploy Bicep Template

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4


    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Bicep Template
      uses: azure/arm-deploy@v2
      with:
        deploymentName: ${{ github.run_number }}
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: demoResourceGroup
        location: uksouth
        template: ./resourceGroup.bicep
        parameters: |
            resourceGroupName=rg-darren-test
            location=uksouth