name: Deploy Bicep Template Test
concurrency: My_Workflow

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

# Define parameters
env:
  REGION: uksouth
  CODE_PATH: deploy/main.bicep

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Run Bicep linter
      run: az bicep build --file ${{ env.CODE_PATH }}

  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to Azure     
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - uses: azure/arm-deploy@v2
      name: Run preflight validation
      with:
        scope: subscription
        region: ${{ env.REGION }}
        deploymentName: ${{ github.run_number }}
        template: ${{ env.CODE_PATH }}
        deploymentMode: Validate    

  preview:
    runs-on: ubuntu-latest
    needs: [lint, validate]
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to Azure     
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - uses: azure/arm-deploy@v2
      name: Run what-if
      with:
        failOnStdErr: false
        scope: subscription
        region: ${{ env.REGION }}
        deploymentName: ${{ github.run_number }}
        template: ${{ env.CODE_PATH }}
        additionalArguments: --what-if  
        deploymentMode: Complete

  deploy:
    runs-on: ubuntu-latest
    environment: Production
    needs: [preview]    

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Bicep Template
      uses: azure/arm-deploy@v2
      with:
        failOnStdErr: false
        scope: subscription
        region: ${{ env.REGION }}
        deploymentName: ${{ github.run_number }}
        template: ${{ env.CODE_PATH }}
        deploymentMode: Complete